namespace DeepSigma.DataAccess.WebSearch.UrlRetriever.Models;

/// <summary>
/// The top-level response returned by <see cref="SearxngClient.SearchRawAsync"/>.
/// </summary>
/// <param name="Results">
/// The ordered list of search results. May be empty but is never <see langword="null"/>.
/// </param>
/// <param name="Metadata">
/// Metadata describing the originating request, the responding instance, timing, and result count.
/// </param>
/// <param name="Warnings">
/// Non-fatal warnings generated during the search, such as disabled engines or partial results.
/// May be empty but is never <see langword="null"/>.
/// </param>
/// <param name="Answers">
/// Direct answers generated by SearXNG or a contributing engine (e.g. calculator results).
/// May be empty but is never <see langword="null"/>.
/// </param>
/// <param name="Corrections">
/// Spelling corrections or alternative query suggestions returned by SearXNG.
/// May be empty but is never <see langword="null"/>.
/// </param>
/// <param name="Suggestions">
/// Related query suggestions returned by SearXNG.
/// May be empty but is never <see langword="null"/>.
/// </param>
public sealed record SearchResponse(
    IReadOnlyList<SearchResult> Results,
    SearchMetadata Metadata,
    IReadOnlyList<SearchWarning> Warnings,
    IReadOnlyList<string> Answers,
    IReadOnlyList<string> Corrections,
    IReadOnlyList<string> Suggestions);
